### ISSUE TITLE
Make release workflow a custom GH action

### ISSUE THREAD

**Issue by kabalin** [moodlehq/moodle-plugin-release#12]
It would be more convenient to use this a custom action, e.g. 

```
on:
  push:
    tags:
      - v*

jobs:
  release-at-moodle-org:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Releasing in the Plugins directory
        uses: moodlehq/moodle-plugin-release@v1
        with:
          token: ${{ secrets.MOODLE_ORG_TOKEN }}
```

Guide on creating custom action and examples are in [docs](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).
